import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond,
  Montserrat, Cinzel_Decorative, Great_Vibes, Pinyon_Script, } from "next/font/google";
import "./globals.css";
import {
  AuthProvider,
} from "@/providers/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant =
  Cormorant_Garamond({
    subsets: ["latin"],
    variable: "--font-title",
  });

const montserrat =
  Montserrat({
    subsets: ["latin"],
    variable: "--font-body",
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cinzelDecorative =
  Cinzel_Decorative({
    subsets: ["latin"],
    weight: ["400", "700", "900"],
    variable: "--font-cinzel-decorative",
    display: "swap",
  });

  const greatVibes =
  Great_Vibes({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-great-vibes",
    display: "swap",
  });

  const pinyonScript = Pinyon_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pinyon-script",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable}
      ${cinzelDecorative.variable}
        ${montserrat.variable}
        ${geistSans.variable}
        ${geistMono.variable}
        ${greatVibes.variable}
        ${pinyonScript.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          {children}
          </AuthProvider></body>
    </html>
  );
}
